var testDiv = document.getElementById("testDiv");
testDiv.addEventListener("click", function() {
  alert("I'm here!");
});

//commented out as location services turned off in browser!

// navigator.geolocation.getCurrentPosition(function(position) {
//   alert("I am here, Latitude: " + position.coords.latitude +
//     "Longitude: " + position.coords.longitude);
// });

function popUp(message) {
  alert(message);
}

function getContent(content, callback) {
  callback(content);
}

getContent("This was generated by a callback", popUp);
